//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanProjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanProjects.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking If Directory Exists.
        /// </summary>
        internal static string ChkdirExist {
            get {
                return ResourceManager.GetString("ChkdirExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Directory.
        /// </summary>
        internal static string DelDir {
            get {
                return ResourceManager.GetString("DelDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting File.
        /// </summary>
        internal static string DelFl {
            get {
                return ResourceManager.GetString("DelFl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Exists.
        /// </summary>
        internal static string DirExists {
            get {
                return ResourceManager.GetString("DirExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Does Not Exist.
        /// </summary>
        internal static string DirNotExist {
            get {
                return ResourceManager.GetString("DirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Directory.
        /// </summary>
        internal static string MoveDir {
            get {
                return ResourceManager.GetString("MoveDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving File.
        /// </summary>
        internal static string MoveFl {
            get {
                return ResourceManager.GetString("MoveFl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Not Rooted.
        /// </summary>
        internal static string PthNtRooted {
            get {
                return ResourceManager.GetString("PthNtRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removeing Project Binding.
        /// </summary>
        internal static string RemBindPrj {
            get {
                return ResourceManager.GetString("RemBindPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Solution Binding.
        /// </summary>
        internal static string RemBindSln {
            get {
                return ResourceManager.GetString("RemBindSln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Read Only .
        /// </summary>
        internal static string RemReadOnly {
            get {
                return ResourceManager.GetString("RemReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Source Files.
        /// </summary>
        internal static string RemSourceFls {
            get {
                return ResourceManager.GetString("RemSourceFls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Rslt {
            get {
                return ResourceManager.GetString("Rslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Tru {
            get {
                return ResourceManager.GetString("Tru", resourceCulture);
            }
        }
    }
}
